// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package generatedmodels

import (
	"context"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (user_id, credential_id, public_key, sign_count)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, credential_id, public_key, sign_count, created_at
`

type CreateCredentialParams struct {
	UserID       int64
	CredentialID []byte
	PublicKey    []byte
	SignCount    int32
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialsByUserID = `-- name: GetCredentialsByUserID :many
SELECT id, user_id, credential_id, public_key, sign_count, created_at 
FROM credentials WHERE user_id = $1
`

func (q *Queries) GetCredentialsByUserID(ctx context.Context, userID int64) ([]Credential, error) {
	rows, err := q.db.Query(ctx, getCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
