// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package generatedmodels

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (user_id, credential_id, public_key, sign_count, backup_eligible, backup_state)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, credential_id, public_key, sign_count, backup_eligible, backup_state, created_at
`

type CreateCredentialParams struct {
	UserID         int64
	CredentialID   []byte
	PublicKey      []byte
	SignCount      int32
	BackupEligible bool
	BackupState    bool
}

type CreateCredentialRow struct {
	ID             int64
	UserID         int64
	CredentialID   []byte
	PublicKey      []byte
	SignCount      int32
	BackupEligible bool
	BackupState    bool
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (CreateCredentialRow, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.BackupEligible,
		arg.BackupState,
	)
	var i CreateCredentialRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialsByUserID = `-- name: GetCredentialsByUserID :many
SELECT id, user_id, credential_id, public_key, sign_count, backup_eligible, backup_state, created_at 
FROM credentials WHERE user_id = $1
`

type GetCredentialsByUserIDRow struct {
	ID             int64
	UserID         int64
	CredentialID   []byte
	PublicKey      []byte
	SignCount      int32
	BackupEligible bool
	BackupState    bool
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetCredentialsByUserID(ctx context.Context, userID int64) ([]GetCredentialsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCredentialsByUserIDRow
	for rows.Next() {
		var i GetCredentialsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.BackupEligible,
			&i.BackupState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredentialSignCountAndFlags = `-- name: UpdateCredentialSignCountAndFlags :exec
UPDATE credentials
SET sign_count = $3,
    backup_eligible = $4,
    backup_state = $5
WHERE user_id = $1 AND credential_id = $2
`

type UpdateCredentialSignCountAndFlagsParams struct {
	UserID         int64
	CredentialID   []byte
	SignCount      int32
	BackupEligible bool
	BackupState    bool
}

func (q *Queries) UpdateCredentialSignCountAndFlags(ctx context.Context, arg UpdateCredentialSignCountAndFlagsParams) error {
	_, err := q.db.Exec(ctx, updateCredentialSignCountAndFlags,
		arg.UserID,
		arg.CredentialID,
		arg.SignCount,
		arg.BackupEligible,
		arg.BackupState,
	)
	return err
}
