// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package generatedmodels

import (
	"database/sql"
)

type Credential struct {
	ID           int64
	UserID       int64
	CredentialID []byte
	PublicKey    []byte
	SignCount    int32
	CreatedAt    sql.NullTime
}

type User struct {
	ID          int64
	Username    string
	DisplayName string
	CreatedAt   sql.NullTime
}
