// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package generatedmodels

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID             int64
	UserID         int64
	CredentialID   []byte
	PublicKey      []byte
	SignCount      int32
	CreatedAt      pgtype.Timestamptz
	BackupState    bool
	BackupEligible bool
}

type User struct {
	ID          int64
	Username    string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}
