// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"
	time "time"
	generatedmodels "webauthn-demo/generatedmodels"

	protocol "github.com/go-webauthn/webauthn/protocol"
	webauthn "github.com/go-webauthn/webauthn/webauthn"
	gomock "go.uber.org/mock/gomock"
)

// MockDBQuerier is a mock of DBQuerier interface.
type MockDBQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockDBQuerierMockRecorder
	isgomock struct{}
}

// MockDBQuerierMockRecorder is the mock recorder for MockDBQuerier.
type MockDBQuerierMockRecorder struct {
	mock *MockDBQuerier
}

// NewMockDBQuerier creates a new mock instance.
func NewMockDBQuerier(ctrl *gomock.Controller) *MockDBQuerier {
	mock := &MockDBQuerier{ctrl: ctrl}
	mock.recorder = &MockDBQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBQuerier) EXPECT() *MockDBQuerierMockRecorder {
	return m.recorder
}

// CreateCredential mocks base method.
func (m *MockDBQuerier) CreateCredential(ctx context.Context, arg generatedmodels.CreateCredentialParams) (generatedmodels.CreateCredentialRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredential", ctx, arg)
	ret0, _ := ret[0].(generatedmodels.CreateCredentialRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredential indicates an expected call of CreateCredential.
func (mr *MockDBQuerierMockRecorder) CreateCredential(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredential", reflect.TypeOf((*MockDBQuerier)(nil).CreateCredential), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockDBQuerier) CreateUser(ctx context.Context, arg generatedmodels.CreateUserParams) (generatedmodels.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(generatedmodels.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockDBQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockDBQuerier)(nil).CreateUser), ctx, arg)
}

// GetCredentialsByUserID mocks base method.
func (m *MockDBQuerier) GetCredentialsByUserID(ctx context.Context, userID int64) ([]generatedmodels.GetCredentialsByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialsByUserID", ctx, userID)
	ret0, _ := ret[0].([]generatedmodels.GetCredentialsByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialsByUserID indicates an expected call of GetCredentialsByUserID.
func (mr *MockDBQuerierMockRecorder) GetCredentialsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialsByUserID", reflect.TypeOf((*MockDBQuerier)(nil).GetCredentialsByUserID), ctx, userID)
}

// GetUserByUsername mocks base method.
func (m *MockDBQuerier) GetUserByUsername(ctx context.Context, username string) (generatedmodels.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(generatedmodels.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockDBQuerierMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockDBQuerier)(nil).GetUserByUsername), ctx, username)
}

// UpdateCredentialSignCountAndFlags mocks base method.
func (m *MockDBQuerier) UpdateCredentialSignCountAndFlags(ctx context.Context, arg generatedmodels.UpdateCredentialSignCountAndFlagsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredentialSignCountAndFlags", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCredentialSignCountAndFlags indicates an expected call of UpdateCredentialSignCountAndFlags.
func (mr *MockDBQuerierMockRecorder) UpdateCredentialSignCountAndFlags(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredentialSignCountAndFlags", reflect.TypeOf((*MockDBQuerier)(nil).UpdateCredentialSignCountAndFlags), ctx, arg)
}

// MockSessionStorer is a mock of SessionStorer interface.
type MockSessionStorer struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStorerMockRecorder
	isgomock struct{}
}

// MockSessionStorerMockRecorder is the mock recorder for MockSessionStorer.
type MockSessionStorerMockRecorder struct {
	mock *MockSessionStorer
}

// NewMockSessionStorer creates a new mock instance.
func NewMockSessionStorer(ctrl *gomock.Controller) *MockSessionStorer {
	mock := &MockSessionStorer{ctrl: ctrl}
	mock.recorder = &MockSessionStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStorer) EXPECT() *MockSessionStorerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionStorer) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionStorerMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionStorer)(nil).Delete), ctx, key)
}

// Load mocks base method.
func (m *MockSessionStorer) Load(ctx context.Context, key string) (*webauthn.SessionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, key)
	ret0, _ := ret[0].(*webauthn.SessionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockSessionStorerMockRecorder) Load(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockSessionStorer)(nil).Load), ctx, key)
}

// Save mocks base method.
func (m *MockSessionStorer) Save(ctx context.Context, key string, data *webauthn.SessionData, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, key, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSessionStorerMockRecorder) Save(ctx, key, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSessionStorer)(nil).Save), ctx, key, data, ttl)
}

// MockWebAuthnProvider is a mock of WebAuthnProvider interface.
type MockWebAuthnProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWebAuthnProviderMockRecorder
	isgomock struct{}
}

// MockWebAuthnProviderMockRecorder is the mock recorder for MockWebAuthnProvider.
type MockWebAuthnProviderMockRecorder struct {
	mock *MockWebAuthnProvider
}

// NewMockWebAuthnProvider creates a new mock instance.
func NewMockWebAuthnProvider(ctrl *gomock.Controller) *MockWebAuthnProvider {
	mock := &MockWebAuthnProvider{ctrl: ctrl}
	mock.recorder = &MockWebAuthnProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebAuthnProvider) EXPECT() *MockWebAuthnProviderMockRecorder {
	return m.recorder
}

// BeginLogin mocks base method.
func (m *MockWebAuthnProvider) BeginLogin(user webauthn.User, opts ...webauthn.LoginOption) (*protocol.CredentialAssertion, *webauthn.SessionData, error) {
	m.ctrl.T.Helper()
	varargs := []any{user}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BeginLogin", varargs...)
	ret0, _ := ret[0].(*protocol.CredentialAssertion)
	ret1, _ := ret[1].(*webauthn.SessionData)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BeginLogin indicates an expected call of BeginLogin.
func (mr *MockWebAuthnProviderMockRecorder) BeginLogin(user any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginLogin", reflect.TypeOf((*MockWebAuthnProvider)(nil).BeginLogin), varargs...)
}

// BeginRegistration mocks base method.
func (m *MockWebAuthnProvider) BeginRegistration(user webauthn.User, opts ...webauthn.RegistrationOption) (*protocol.CredentialCreation, *webauthn.SessionData, error) {
	m.ctrl.T.Helper()
	varargs := []any{user}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BeginRegistration", varargs...)
	ret0, _ := ret[0].(*protocol.CredentialCreation)
	ret1, _ := ret[1].(*webauthn.SessionData)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BeginRegistration indicates an expected call of BeginRegistration.
func (mr *MockWebAuthnProviderMockRecorder) BeginRegistration(user any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginRegistration", reflect.TypeOf((*MockWebAuthnProvider)(nil).BeginRegistration), varargs...)
}

// FinishLogin mocks base method.
func (m *MockWebAuthnProvider) FinishLogin(user webauthn.User, session webauthn.SessionData, response *http.Request) (*webauthn.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishLogin", user, session, response)
	ret0, _ := ret[0].(*webauthn.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishLogin indicates an expected call of FinishLogin.
func (mr *MockWebAuthnProviderMockRecorder) FinishLogin(user, session, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishLogin", reflect.TypeOf((*MockWebAuthnProvider)(nil).FinishLogin), user, session, response)
}

// FinishRegistration mocks base method.
func (m *MockWebAuthnProvider) FinishRegistration(user webauthn.User, session webauthn.SessionData, response *http.Request) (*webauthn.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishRegistration", user, session, response)
	ret0, _ := ret[0].(*webauthn.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishRegistration indicates an expected call of FinishRegistration.
func (mr *MockWebAuthnProviderMockRecorder) FinishRegistration(user, session, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishRegistration", reflect.TypeOf((*MockWebAuthnProvider)(nil).FinishRegistration), user, session, response)
}
